name: Frontend CI/CD

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Chrome Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libasound2-dev \
          libx11-xcb1 \
          libnss3 \
          libxss1 \
          libappindicator3-1 \
          libatk-bridge2.0-0 \
          libgtk-3-0 \
          fonts-liberation \
          xdg-utils \
          wget

    - name: Install Node Dependencies
      run: npm install

    - name: Run Angular Tests
      run: npm run test -- --watch=false --browsers=ChromeHeadless

    - name: Build Angular App
      run: npm run build -- --configuration=production

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build and Push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/fixithub-frontend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/fixithub-frontend:latest
